AllCops:
  Exclude:
    - Berksfile
    - recipes/basic.rb
    - attributes/*.rb

# Customize rules
Metrics/LineLength:
  Max: 95

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 45