# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  ruby272:
    docker:
      - image: circleci/ruby:2.7.2-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: gem system updates
          command: |
            gem update --system
            gem update bundler
            gem --version

      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1

      - run: bundle install --path vendor/bundle
      - run: yarn install

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - node_modules

      - run:
          name: Rails Migrate
          command: ./bin/rails db:migrate RAILS_ENV=test
      - run:
          name: Webpacker Compile
          command: ./bin/rails webpacker:compile RAILS_ENV=test
      - run:
          name: Run Tests
          command: ./bin/rails test

      # Disabled because CircleCI wants $30/month to build docker images :-(
      #
      # - setup_remote_docker:
      #     version: 19.03.13
      #     docker_layer_caching: true

      # # build and push pwpush-postgres Docker image
      # - run: |
      #     TAG=1.7.$CIRCLE_BUILD_NUM
      #     docker build -t pglombardo/pwpush-postgres:$TAG .
      #     echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #     docker push pglombardo/pwpush-postgres:$TAG

      # # build and push pwpush-ephemeral Docker image
      # - run: |
      #     TAG=1.7.$CIRCLE_BUILD_NUM
      #     docker build -t pglombardo/pwpush-ephemeral:$TAG .
      #     echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #     docker push pglombardo/pwpush-ephemeral:$TAG

workflows:
  version: 2
  build:
    jobs:
      - ruby272

