# Global Application Defaults

# This is initially for internal settings.  If all goes well using
# this new config gem, then we'll migrate entirely to the new Settings
# format for private instances too.

# Logins are disabled by default since they require an MTA (email) server
# available to send emails through.
# For instructions on how to enable logins, see this page:
# https://github.com/pglombardo/PasswordPusher/discussions/276
enable_logins: false

# The domain (without protocol) where this instance is hosted
# Used in generating fully qualified URLs.
# host_domain: 'pwpush.com'

# The protocol to reach the domain above
# Used in generating fully qualified URLs.
host_protocol: 'https'

# When logins are enabled, an SMTP server is required to send emails to users
# for things such as forgot password, unlock account, confirm account etc.
# If `enable_logins` is set to true above, the following _are required_ to be
# filled out with valid values.
mail:
  raise_delivery_errors: false
  # smtp_address: smtp.example.com
  # smtp_user_name: 'apikey'
  # smtp_password: ''
  smtp_port: 587
  smtp_authentication: 'plain'
  smtp_starttls: true
  smtp_open_timeout: 10
  smtp_read_timeout: 10

  # Configure the e-mail address which will be shown as 'From' in emails
  # See config/initializers/devise.rb where this is used
  # mailer_sender: '"Password Pusher" <pglombardo@pwpush.com>'

# List of supported languages indexed by language code.  This is used
# to build the in application language menu.
#
# <language code>: '<language name>'
language_codes:
  ca: 'Català'
  cs: 'Čeština'
  da: 'Dansk'
  de: 'Deutsch'
  en: 'English'
  es: 'Español'
  fr: 'Français'
  hu: 'Magyar'
  it: 'Italiano'
  nl: 'Nederlands'
  'no': 'Norsk' # _no_ keyword in Ruby evaluates to false :-(
  pl: 'Polski'
  'pt-BR': 'Português'
  sr: 'Српски'
  sv: 'Svenska'

# The default language for the application.  This must be one of the
# valid/supported language codes from the list above.
# Example: default_locale: :es
# Environment Variable Override: PWP__DEFAULT_LOCALE='es'
default_locale: :en

