version: '2.1'

services:
  postgres:
    image: docker.io/postgres:10
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: passwordpusher_user
      POSTGRES_PASSWORD: passwordpusher_passwd
      POSTGRES_DB: passwordpusher_db

  passwordpusher:
    image: docker.io/pglombardo/pwpush-postgres:release
    ports:
      - "5100:5100"
    depends_on:
      - postgres
    links:
     - postgres:postgres
